version: '3.3'

services:
  mongo:
    image: mongo
    container_name: people-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data
volumes:
  mongo-data: