apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-back
  labels:
    app: people-back1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: people-back1
  template:
    metadata:
      labels:
        app: people-back1
    spec:
      containers:
        - name: people-back1
          image: josefirstacr.azurecr.io/test
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
   name: people-balancer
spec:
  selector:
    app: people-balancer
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer