---
server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      password: password
      username: root
      authentication-database: admin
      database: bank-people-db

