---
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:p20pl3bank@cluster0.ykscc.mongodb.net/bank-people-db?retryWrites=true&w=majority
      #port: 27018
      #password: p20pl3bank
      #username: root
      #authentication-database: admin
      #database: bank-people-db

